# Generated by Django 6.0.7 on 2026-07-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoemAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("freshness", models.SmallIntegerField(blank=True, null=True)),
                ("emotional_density", models.SmallIntegerField(blank=True, null=True)),
                ("voice", models.SmallIntegerField(blank=True, null=True)),
                ("completeness", models.SmallIntegerField(blank=True, null=True)),
                ("anti_repeat", models.SmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("model_name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="app.poem",
                    ),
                ),
            ],
            options={
                "db_table": "app_poem_assessment",
            },
        ),
    ]
