# Generated by Django 6.0.7 on 2026-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="poem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
