# Generated by Django 6.0.7 on 2026-07-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_username_to_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("refresh_token", models.CharField(db_index=True)),
                ("expired_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.author")),
            ],
            options={
                "db_table": "app_refresh_token",
            },
        ),
    ]
