# Generated by Django 6.0.7 on 2026-07-16 16:16

import django.db.models.deletion
import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_poem_collection_nullable"),
    ]

    operations = [
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name="PoemEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vector", pgvector.django.vector.VectorField(dimensions=1024)),
                ("model_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="embedding", to="app.poem"
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["vector"],
                        m=16,
                        name="app_poem_embedding_vector_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
