# Generated by Django 6.0.7 on 2026-07-16 17:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_poemembedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poemembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
