# Generated by Django 6.0.7 on 2026-07-16 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_poemembedding_vector"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="poemembedding",
            table="app_poem_embedding",
        ),
    ]
