# Generated by Django 6.0.7 on 2026-07-17 04:35

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_poemembedding_table"),
    ]

    operations = [
        # Existing 768-dim vectors are incompatible with the new 1024-dim column
        # (model switched to BAAI/bge-m3). Clear them so ALTER COLUMN succeeds;
        # the corpus is re-embedded afterwards via `backfill_embeddings`.
        migrations.RunSQL(
            sql="TRUNCATE TABLE app_poem_embedding",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="poemembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
